### ISSUE TITLE
Characterization of unknown cells

### ISSUE THREAD

**Issue by thesourcerer8** [stineje/CharLib#3]
Please enhance CharLib to be able to characterize cells that aren't registered yet, like e.g. lctime does. At the moment CharLib gives the following error message:
![grafik](https://user-images.githubusercontent.com/6086693/204287031-3a238b64-f0a7-4c19-a852-38088cf595cb.png)
I have attached the CharLib.cmd that caused the error:
[CharLib.cmd.txt](https://github.com/stineje/CharLib/files/10104073/CharLib.cmd.txt)
The standard cell files are available here: https://pdk.libresilicon.com/dist/StdCellLib_20221127_GF180_WIP.tgz

**Comment by infinitymdm** [comment]
I believe this should be resolved as of 0.9, but I admit I haven't tested it with the PDK you linked. Once the work on the next release is done I may have time to try testing it.

**Comment by infinitymdm** [comment]
I was able to run a few simple cells from that library using this YAML config:

```
settings:
    lib_name:   GF180_libre
    named_nodes:
        vdd:
            name: VDD
            voltage: 3.3
        vss:
            name: GND
            voltage: 0
    cell_defaults:
        models: [/home/marcus/Downloads/GF180/Tech/libresilicon.m]
        slews: [0.015, 0.04, 0.2]
        loads: [0.05, 0.15, 0.45]
        simulation_timestep: auto
cells:
    INV:
        netlist: /home/marcus/Downloads/GF180/Catalog/INV.sp
        inputs: [A]
        outputs: ['Y']
        functions: [Y=~A]
    AND4:
        netlist: /home/marcus/Downloads/GF180/Catalog/AND4.sp
        inputs: [A, B, C, D]
        outputs: [Z]
        functions: [Z=(A&B)&(C&D)]
        test_vectors:
            - ['01','1','1','1','01']
            - ['1','01','1','1','01']
            - ['1','1','01','1','01']
            - ['1','1','1','01','01']
            - ['10','1','1','1','10']
            - ['1','10','1','1','10']
            - ['1','1','10','1','10']
            - ['1','1','1','10','10']
```

In the process I did discover some issues with the test vector generation (thus the list of test vectors on the AND4 cell). See #16 for more info there.
